name: Publish @xiezijie/vueui To Npm

on:
  push:
    branches: [publish]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - name: Install modules
        run: cd packages/vueui && pnpm install
      - name: Build
        run: cd packages/vueui && pnpm run build
      - name: Publish
        run: cd packages/vueui/dist && pnpm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致